name: blooddonation
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  dio: ^5.0.0
  intl: ^0.18.0
  flutter_svg: ^2.0.1
  cached_network_image: ^3.2.3
  permission_handler: ^10.2.0
  percent_indicator: ^4.2.2
  store_redirect: ^2.0.1
  sizer: ^2.0.15
  smooth_page_indicator: ^1.1.0
  image_picker: ^0.8.7+5
  firebase_storage: ^11.2.1
  mailer: ^6.0.1
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter_screenutil: ^5.7.0

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/Images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/comfortaa-regular.ttf
        - asset: assets/fonts/comfortaa-bold.ttf
          weight: 700

        - asset: assets/fonts/comfortaa-light.ttf

        - asset: assets/fonts/comfortaa-medium.ttf

        - asset: assets/fonts/comfortaa-thin.ttf

        - asset: assets/fonts/comfortaa-italic.ttf
          weight: 700
          
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo-regular.ttf